api:
  url: https://XXX.contrastsecurity.com/Contrast
  api_key: XXX
  service_key: XXX
  user_name: XX
application:
  name: sql-ctf
server:
  name: CTF-Server
protect:
  enabled: false
assess:
  enabled: true
agent:
  logger:
    level: INFO
